<?php 
/***************************************************************************
*                                                                          *
*   (c) 2004 Vladimir V. Kalynyak, Alexey V. Vinokurov, Ilya M. Shalnev    *
*                                                                          *
* This  is  commercial  software,  only  users  who have purchased a valid *
* license  and  accept  to the terms of the  License Agreement can install *
* and use this program.                                                    *
*                                                                          *
****************************************************************************
* PLEASE READ THE FULL TEXT  OF THE SOFTWARE  LICENSE   AGREEMENT  IN  THE *
* "copyright.txt" FILE PROVIDED WITH THIS DISTRIBUTION PACKAGE.            *
****************************************************************************/ ?>

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo Mage::helper('searchanise')->__('Searchanise');?></h3></td>
        </tr>
    </table>
</div>
<div class="snize" id="snize_container"></div>

<?php
    Mage::helper('searchanise/ApiSe')->checkImportIsDone();
    $searchanise_options = Mage::helper('searchanise/ApiSe')->getAddonOptions();
    
    $searchanise_options['options_link'] = $this->getUrl(Mage::helper('searchanise/ApiSe')->getOptionsLink());
    $searchanise_options['re_sync_link'] = $this->getUrl(Mage::helper('searchanise/ApiSe')->getReSyncLink());
    $searchanise_options['connect_link'] = $this->getUrl(Mage::helper('searchanise/ApiSe')->getConnectLink());
    
    $se_service_url = Mage::helper('searchanise/ApiSe')->getServiceUrl(false);
?>

<script type="text/javascript">
//<![CDATA[
    SearchaniseAdmin = {};
    
    SearchaniseAdmin.host        = '<?php echo $se_service_url;?>';
    SearchaniseAdmin.PrivateKey  = '<?php echo $searchanise_options['parent_private_key'];?>';
    SearchaniseAdmin.OptionsLink = '<?php echo $searchanise_options['options_link'];?>';
    SearchaniseAdmin.ReSyncLink  = '<?php echo $searchanise_options['re_sync_link'];?>';
    SearchaniseAdmin.LastRequest = '<?php echo $searchanise_options['last_request'];?>';
    SearchaniseAdmin.LastResync  = '<?php echo $searchanise_options['last_resync'];?>';
    SearchaniseAdmin.ConnectLink = '<?php echo $searchanise_options['connect_link'];?>';
    SearchaniseAdmin.AddonStatus = '<?php echo $searchanise_options['addon_status'];?>';
    
    SearchaniseAdmin.Engines = [];
    
    <?php
        if(!empty($searchanise_options['parent_private_key'])) {
            $stores = Mage::app()->getStores();
            
            if(!empty($stores))
            {
                foreach($stores as $k_store => $store)
                {
                    $price_format = Mage::helper('searchanise/ApiSe')->getPriceFormat($store);
                    $private_key = $searchanise_options['private_key'][$store->getId()];
                    $export_status = empty($searchanise_options['export_status'][$store->getId()]) ? 'none' : $searchanise_options['export_status'][$store->getId()];
                    $price_format['after'] = $price_format['after'] ? 'true' : 'false';
                    
                    echo "SearchaniseAdmin.Engines.push({";
                        echo "PrivateKey:   '{$private_key}',";
                        echo "LangCode:     '{$store->getCode()}',";
                        echo "Name :        '{$store->getName()}',";
                        echo "ExportStatus: '{$export_status}',";
                        echo "PriceFormat: {";
                            echo "rate :               '{$price_format['rate']}',";
                            echo "decimals:            '{$price_format['decimals']}',";
                            echo "decimals_separator:  '{$price_format['decimals_separator']}',";
                            echo "thousands_separator: '{$price_format['thousands_separator']}',";
                            echo "symbol:              '{$price_format['symbol']}',";
                            echo "after:                {$price_format['after']}";
                        echo "}";
                    echo "});";
                }
            }
        }
    ?>
//]]>
</script>

<script type="text/javascript" src="<?php echo $se_service_url;?>/js/init.js"></script>